org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtbss
mod_name = GregTech:BlueSky Symphony
mod_version = 1.0.0
mod_description = GregTech:BlueSky Symphony
mod_license = GPLv3.0 license
mod_url = https://github.com/ialdaiaxiariyay/GregTech-BlueSkySymphony
mod_issue_tracker =https://github.com/ialdaiaxiariyay/GregTech-BlueSkySymphony/issues
maven_group = top.ialdaiaxiariyay.gtbss